// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmKpyHhXPkYW16aFL6DpT2i_zyVczlwbw',
    appId: '1:249063566811:web:51ff446b0cfc51fe54cbfe',
    messagingSenderId: '249063566811',
    projectId: 'teste-54d00',
    authDomain: 'teste-54d00.firebaseapp.com',
    storageBucket: 'teste-54d00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJ2y_zhB3G7N5bnRT9gy9rWo5LjcoCjI',
    appId: '1:249063566811:android:1f3ebc63b5eeeed254cbfe',
    messagingSenderId: '249063566811',
    projectId: 'teste-54d00',
    storageBucket: 'teste-54d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0Dvcbg49dfkoFBQRskZ09QBb-PaWOpQ',
    appId: '1:249063566811:ios:30749f7e824bbf2054cbfe',
    messagingSenderId: '249063566811',
    projectId: 'teste-54d00',
    storageBucket: 'teste-54d00.appspot.com',
    iosBundleId: 'com.example.informaticStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0Dvcbg49dfkoFBQRskZ09QBb-PaWOpQ',
    appId: '1:249063566811:ios:30749f7e824bbf2054cbfe',
    messagingSenderId: '249063566811',
    projectId: 'teste-54d00',
    storageBucket: 'teste-54d00.appspot.com',
    iosBundleId: 'com.example.informaticStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmKpyHhXPkYW16aFL6DpT2i_zyVczlwbw',
    appId: '1:249063566811:web:74c2227041cd620654cbfe',
    messagingSenderId: '249063566811',
    projectId: 'teste-54d00',
    authDomain: 'teste-54d00.firebaseapp.com',
    storageBucket: 'teste-54d00.appspot.com',
  );
}
